"""Add telegram integration columns to user table

Revision ID: f4d672d0b5d3
Revises: rev_key_roulette
Create Date: 2025-12-29 13:22:55.576270+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d672d0b5d3'
down_revision = 'rev_key_roulette'
branch_labels = None
depends_on = None


from sqlalchemy import text

def _column_exists(table: str, column: str) -> bool:
    conn = op.get_bind()
    return bool(
        conn.execute(
            text(
                """
                SELECT 1
                FROM information_schema.columns
                WHERE table_schema = DATABASE()
                  AND table_name = :table
                  AND column_name = :column
                """
            ),
            {"table": table, "column": column},
        ).scalar()
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _column_exists('user', 'telegram_id'):
        op.add_column('user', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
        try:
            op.create_index(op.f('ix_user_telegram_id'), 'user', ['telegram_id'], unique=True)
        except Exception:
            pass # Index likely exists

    if not _column_exists('user', 'telegram_username'):
        op.add_column('user', sa.Column('telegram_username', sa.String(length=100), nullable=True))
    if not _column_exists('user', 'telegram_is_blocked'):
        op.add_column('user', sa.Column('telegram_is_blocked', sa.Boolean(), server_default='0', nullable=False))
    if not _column_exists('user', 'telegram_join_count'):
        op.add_column('user', sa.Column('telegram_join_count', sa.Integer(), server_default='0', nullable=False))
    if not _column_exists('user', 'first_login_at'):
        op.add_column('user', sa.Column('first_login_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_telegram_id'), table_name='user')
    op.drop_column('user', 'first_login_at')
    op.drop_column('user', 'telegram_join_count')
    op.drop_column('user', 'telegram_is_blocked')
    op.drop_column('user', 'telegram_username')
    op.drop_column('user', 'telegram_id')
    # ### end Alembic commands ###
