"""Add next_season_seed to user

Revision ID: cd4588841c24
Revises: 23a5aba9554e
Create Date: 2025-12-28 00:48:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd4588841c24'
down_revision = '23a5aba9554e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('next_season_seed', sa.Integer(), server_default='0', nullable=False))
    # Consolidating missing columns from previous lost migrations
    op.add_column('user', sa.Column('last_free_ticket_claimed_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('has_completed_onboarding', sa.Boolean(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_completed_onboarding')
    op.drop_column('user', 'last_free_ticket_claimed_at')
    op.drop_column('user', 'next_season_seed')
    # ### end Alembic commands ###
