"""Add telegram integration columns to user table

Revision ID: f4d672d0b5d3
Revises: rev_key_roulette
Create Date: 2025-12-29 13:22:55.576270+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d672d0b5d3'
down_revision = 'rev_key_roulette'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.add_column('user', sa.Column('telegram_username', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('telegram_is_blocked', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('user', sa.Column('telegram_join_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user', sa.Column('first_login_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_telegram_id'), 'user', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_telegram_id'), table_name='user')
    op.drop_column('user', 'first_login_at')
    op.drop_column('user', 'telegram_join_count')
    op.drop_column('user', 'telegram_is_blocked')
    op.drop_column('user', 'telegram_username')
    op.drop_column('user', 'telegram_id')
    # ### end Alembic commands ###
