"""Add imported metrics to admin profile

Revision ID: 23a5aba9554e
Revises: 2e5c3b701c31
Create Date: 2025-12-27 19:48:26.551032+09:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = '23a5aba9554e'
down_revision = '2e5c3b701c31'
branch_labels = None
depends_on = None


def _column_exists(table: str, column: str) -> bool:
    conn = op.get_bind()
    return bool(
        conn.execute(
            text(
                """
                SELECT 1
                FROM information_schema.columns
                WHERE table_schema = DATABASE()
                  AND table_name = :table
                  AND column_name = :column
                """
            ),
            {"table": table, "column": column},
        ).scalar()
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _column_exists('admin_user_profile', 'total_active_days'):
        op.add_column('admin_user_profile', sa.Column('total_active_days', sa.Integer(), nullable=True))
    if not _column_exists('admin_user_profile', 'days_since_last_charge'):
        op.add_column('admin_user_profile', sa.Column('days_since_last_charge', sa.Integer(), nullable=True))
    if not _column_exists('admin_user_profile', 'last_active_date_str'):
        op.add_column('admin_user_profile', sa.Column('last_active_date_str', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_user_profile', 'last_active_date_str')
    op.drop_column('admin_user_profile', 'days_since_last_charge')
    op.drop_column('admin_user_profile', 'total_active_days')
    # ### end Alembic commands ###
