"""add inventory models

Revision ID: 8f568c60bb17
Revises: add_mission_approval
Create Date: 2026-01-01 04:01:40.797714+09:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f568c60bb17'
down_revision = 'add_mission_approval'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    if 'user_inventory_item' not in existing_tables:
        op.create_table('user_inventory_item',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('item_type', sa.String(length=50), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'item_type', name='uq_user_inventory_item_user_item')
        )
        op.create_index(op.f('ix_user_inventory_item_id'), 'user_inventory_item', ['id'], unique=False)
        op.create_index(op.f('ix_user_inventory_item_item_type'), 'user_inventory_item', ['item_type'], unique=False)
        op.create_index(op.f('ix_user_inventory_item_user_id'), 'user_inventory_item', ['user_id'], unique=False)

    if 'user_inventory_ledger' not in existing_tables:
        op.create_table('user_inventory_ledger',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('item_type', sa.String(length=50), nullable=False),
        sa.Column('change_amount', sa.Integer(), nullable=False),
        sa.Column('balance_after', sa.Integer(), nullable=False),
        sa.Column('reason', sa.String(length=100), nullable=False),
        sa.Column('related_id', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_user_inventory_ledger_id'), 'user_inventory_ledger', ['id'], unique=False)
        op.create_index(op.f('ix_user_inventory_ledger_item_type'), 'user_inventory_ledger', ['item_type'], unique=False)
        op.create_index(op.f('ix_user_inventory_ledger_user_id'), 'user_inventory_ledger', ['user_id'], unique=False)

    if 'vault_withdrawal_request' not in existing_tables:
        op.create_table('vault_withdrawal_request',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('admin_memo', sa.String(length=255), nullable=True),
        sa.Column('processed_at', sa.DateTime(), nullable=True),
        sa.Column('processed_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_vault_withdrawal_request_id'), 'vault_withdrawal_request', ['id'], unique=False)
        op.create_index(op.f('ix_vault_withdrawal_request_user_id'), 'vault_withdrawal_request', ['user_id'], unique=False)
    op.alter_column('season_pass_config', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_config', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_level', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_level', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_progress', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_progress', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_reward_log', 'claimed_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_reward_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('season_pass_stamp_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('season_pass_stamp_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_reward_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_reward_log', 'claimed_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_progress', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_progress', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_level', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_level', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_config', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('season_pass_config', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_index(op.f('ix_vault_withdrawal_request_user_id'), table_name='vault_withdrawal_request')
    op.drop_index(op.f('ix_vault_withdrawal_request_id'), table_name='vault_withdrawal_request')
    op.drop_table('vault_withdrawal_request')
    op.drop_index(op.f('ix_user_inventory_ledger_user_id'), table_name='user_inventory_ledger')
    op.drop_index(op.f('ix_user_inventory_ledger_item_type'), table_name='user_inventory_ledger')
    op.drop_index(op.f('ix_user_inventory_ledger_id'), table_name='user_inventory_ledger')
    op.drop_table('user_inventory_ledger')
    op.drop_index(op.f('ix_user_inventory_item_user_id'), table_name='user_inventory_item')
    op.drop_index(op.f('ix_user_inventory_item_item_type'), table_name='user_inventory_item')
    op.drop_index(op.f('ix_user_inventory_item_id'), table_name='user_inventory_item')
    op.drop_table('user_inventory_item')
    # ### end Alembic commands ###
