"""add user streak

Revision ID: 20260106_0730_add_user_streak
Revises: 20260104_2300_add_trial_season_and_schedule
Create Date: 2026-01-06 07:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260106_0730_add_user_streak'
down_revision = '20260104_2300_add_trial_season_and_schedule'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user', sa.Column('last_streak_updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('idx_user_login_streak'), 'user', ['login_streak'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_user_login_streak'), table_name='user')
    op.drop_column('user', 'last_streak_updated_at')
    op.drop_column('user', 'login_streak')
    # ### end Alembic commands ###
