ALTER TABLE user_game_wallet MODIFY COLUMN token_type ENUM('ROULETTE_COIN', 'DICE_TOKEN', 'LOTTERY_TICKET', 'CC_COIN', 'GOLD_KEY', 'DIAMOND_KEY', 'DIAMOND') NOT NULL;
ALTER TABLE user_game_wallet_ledger MODIFY COLUMN token_type ENUM('ROULETTE_COIN', 'DICE_TOKEN', 'LOTTERY_TICKET', 'CC_COIN', 'GOLD_KEY', 'DIAMOND_KEY', 'DIAMOND') NOT NULL;
