SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE ranking_daily;
TRUNCATE TABLE external_ranking_data;
TRUNCATE TABLE external_ranking_reward_log;
TRUNCATE TABLE roulette_log;
TRUNCATE TABLE dice_log;
TRUNCATE TABLE lottery_log;
TRUNCATE TABLE user_activity;
TRUNCATE TABLE user_activity_event;
TRUNCATE TABLE user_event_log;
TRUNCATE TABLE user_xp_event_log;
TRUNCATE TABLE user_game_wallet_ledger;
TRUNCATE TABLE user_cash_ledger;
TRUNCATE TABLE season_pass_progress;
TRUNCATE TABLE season_pass_reward_log;
TRUNCATE TABLE season_pass_stamp_log;
TRUNCATE TABLE user_level_progress;
TRUNCATE TABLE user_level_reward_log;
TRUNCATE TABLE user_game_wallet;
SET FOREIGN_KEY_CHECKS=1;
